# Generated by Django 4.1.13 on 2025-05-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_manual_update"),
    ]

    operations = [
        # Eliminamos las operaciones ALTER COLUMN que no son compatibles con Djongo
    ]
